version: "3.9"

services:
  django_backend:
    build:
      context: ./hotel_list_backend
    container_name: hotel_django_backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=sub-root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=hotel_lister_db
    ports:
      - "8000:8000"
    volumes:
      - ./hotel_list_backend:/app
    depends_on:
      - db

  node_frontend:
    build:
      context: ./hotel_list_frontend
    container_name: hotel_node_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./hotel_list_frontend:/app
    depends_on:
      - django_backend

  db:
    image: mysql:8
    container_name: hotel_mysql_db
    environment:
      MYSQL_DATABASE: hotel_lister_db
      MYSQL_USER: sub-root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: your_root_password
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"     # This allows empty root password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
