version: "3.9"

services:
  backend:
    build:
      context: ./hotel_list_backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hotel_list_backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - frontend

  frontend:
    build:
      context: ./hotel_list_frontend
    container_name: react-frontend
    volumes:
      - ./hotel_list_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
