version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: hotel_lister_db_docker
      MYSQL_USER: hotel_app_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: REPLACE_WITH_YOUR_MYSQL_ROOT_PASSWORD
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"     # IF YOU WANT TO ALLOW EMPTY PASSWORDS
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  django:
    build:
      context: ./hotel_list_backend
    container_name: django_app
    restart: unless-stopped
    volumes:
      - ./hotel_list_backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_NAME=hotel_lister_db_docker
      - DB_USER=hotel_app_user
      - DB_PASSWORD=1234
      - DB_HOST=mysql

  nextjs:
    build:
      context: ./hotel_list_frontend
    container_name: nextjs_app
    restart: unless-stopped
    volumes:
      - ./hotel_list_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django
    environment:
      - NEXT_PUBLIC_API_URL=http://django:8000

volumes:
  mysql_data:
